# Generated by Django 6.0.6 on 2026-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(help_text='The standard FEN notation representing the board state.', max_length=255, unique=True)),
                ('solution', models.CharField(help_text='The consecutive correct UCI moves separated by spaces.', max_length=255)),
                ('rating', models.IntegerField(default=1200, help_text='The estimated ELO rating/difficulty of the puzzle.')),
                ('description', models.TextField(blank=True, help_text='Optional description of the tactical theme or tactical motives.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
